ARG REPO_LOCATION=''
ARG NVHPC_VERSION='23.11'
ARG CUDA_VERSION='12.3'
ARG UBUNTU_VERSION='22.04'
ARG PROXY=none
FROM ${REPO_LOCATION}nvcr.io/nvidia/nvhpc:${NVHPC_VERSION}-runtime-cuda${CUDA_VERSION}-ubuntu${UBUNTU_VERSION}


# baseline
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y lsb-release
RUN apt-get install -y sudo python3 python3-pip python3-setuptools
RUN groupadd -g 1000 yongwoo && \
    useradd -m -u 1000 -g 1000 yongwoo && \
    echo "yongwoo ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
    chmod 0440 /etc/sudoers && \
    chmod g+w /etc/passwd


# ubuntu package dependencies
# libsm6 libxext6 libxrender1 : needed by opencv
# cmake protobuf-compiler libprotoc-dev : needed by onnx
# graphviz : needed by tvm
# swig : needed by model selection tool
# curl vim git wget gdb : needeed by baseline dev
RUN bash -c 'apt-get update;\
             apt-get install -y cmake libprotobuf-dev protobuf-compiler libprotoc-dev graphviz swig curl vim git wget gdb nano zip pkg-config libgtk-3-dev libyaml-cpp-dev;'


WORKDIR /home/yongwoo
USER yongwoo
RUN mkdir -p /home/yongwoo/ti-processor-sdk-linux-edgeai-j721e-evm-09_02_00_05
RUN mkdir -p /home/yongwoo/workspace
RUN mkdir -p /home/yongwoo/workspace/images/BOOT
RUN mkdir -p /home/yongwoo/workspace/images/rootfs
RUN mkdir -p /home/yongwoo/workspace/images/kernelfs
